port: '8000'
db:
  username: 'postgres'
  password: '123123'
  host: 'localhost'
  port: '5432'
  dbname: 'postgres'
  sslmode: 'disable'
mysql:
  username: 'root'
  password: '000000'
  host: '0.0.0.0'
  port: '3306'
  dbname: 'go'
